### ISSUE TITLE
Sample Data Issue

### ISSUE THREAD

**Issue by jgeller112** [mne-tools/mne-r#1]
Hi! 

I was trying to test out some of the functions with the sample data, but got an error when I tried to download it: 

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Hash mismatch for downloaded file /Users/gellr/mne_data/MNE-sample-data-processed.tar.gz.part, expected fc2d5b9eb0a144b1d6ba84dc3b983602 but got 0949759a5d40fb2ddde93d3401055f0d`

**Comment by dengemann** [comment]
Hi! Can you try to delete the incompletely downloaded file and retry? This is most likely no issue with MNE but with with your internet connection or the server.

**Comment by jgeller112** [comment]
That worked! I am excited to give this a try!

**Comment by dengemann** [comment]
@jgeller112 my apologies. I inadvertently deleted your comment :-( while trying to express my shared enthusiasm through a +1 emoji. Let me know how your explorations proceed :)
