### ISSUE TITLE
Annotations get wring onset times

### ISSUE THREAD

**Issue by SeHellmann** [mne-tools/mne-r#18]
Hello,

I tried reproducing a python-mne analysis using mne-r, but got different results. 
I am not sure, whether this really causes the different results (i.e. whether the onset in the datetime format are really used internally), but when using the R functions I get:
```
> mne$`__version__`
[1] "1.8.0"
> annotations <-  mne$Annotations(onset = c(0, 62, 90),
+                                 duration = c(30, 20, 35),
+                                 description = "bad artefact")
> raw$set_annotations(annotations)
<RawEDF | SBJ_01.bdf, 69 x 2250752 (4396.0 s), ~1.16 GB, data loaded>
> raw$annotations$to_data_frame()
                onset duration  description
1 2017-05-22 17:00:08       30 bad artefact
2 2017-05-22 17:01:10       20 bad artefact
3 2017-05-22 17:01:38       35 bad artefact
> raw$info['meas_date']
[1] "2017-05-22 15:00:08 UTC"
```

While for the python-mne, it gives:
```
>>> mne.__version__
'1.8.0'
>>> annotations = mne.Annotations(onset = [0, 62, 90],
...                               duration = [30, 20, 35],
...                               description = "bad artefact")
>>> raw.set_annotations(annotations)
<RawEDF | SBJ_01.bdf, 69 x 2250752 (4396.0 s), ~1.16 GB, data loaded>
>>> raw.annotations.to_data_frame()
                onset  duration   description
0 2017-05-22 15:00:08      30.0  bad artefact
1 2017-05-22 15:01:10      20.0  bad artefact
2 2017-05-22 15:01:38      35.0  bad artefact
```

I tried specifying the `orig_time`  argument, using a datetime object, but it seems that providing a datetime, which is generated within R is not recognized as such: 
```
> datetime <- import("datetime")
> annotations <-  mne$Annotations(onset = c(0, 62, 90),
+                                 duration = c(30, 20, 35),
+                                 description = "bad artefact",
+                                 orig_time = datetime$datetime$strptime(as.character(raw$info['meas_date']),
+                                                                        "%Y-%m-%d %H:%M:%S"))
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Date must be datetime object in UTC: array(['2017-05-22T13:00:08.000000000'], dtype='datetime64[ns]')
```

I hope, this is enough detail and illustrates the problem.

**Comment by agramfort** [comment]
how did you get the raw object? set_annotations's behavior is affected by
raw.info["first_samp"] and raw.info["meas_date"]

**Comment by SeHellmann** [comment]
I am reading a .bdf file using: `raw = mne$io$read_raw_bdf("SBJ_01.bdf", preload =TRUE)` in R, and in python: `raw = mne.io.read_raw_bdf("SBJ_01.bdf", preload =True)`.
However, neither in the python object nor in R the info has an attribute called `first_samp`.
In R:
```
> names(raw$info)
 [1] "acq_pars"           "acq_stim"           "bads"               "ch_names"           "chs"                "comps"              "ctf_head_t"         "custom_ref_applied"
 [9] "description"        "dev_ctf_t"          "dev_head_t"         "device_info"        "dig"                "events"             "experimenter"       "file_id"           
[17] "gantry_angle"       "helium_info"        "highpass"           "hpi_meas"           "hpi_results"        "hpi_subsystem"      "kit_system_id"      "line_freq"         
[25] "lowpass"            "meas_date"          "meas_id"            "nchan"              "proc_history"       "proj_id"            "proj_name"          "projs"             
[33] "sfreq"              "subject_info"       "utc_offset"         "xplotter_layout" 
```
In python: 
```
>>> raw.info
<Info | 8 non-empty values
 bads: []
 ch_names: Fp1, AF7, AF3, F1, F3, F5, F7, FT7, FC5, FC3, FC1, C1, C3, C5, ...
 chs: 72 EEG, 1 Stimulus
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 104.0 Hz
 meas_date: 2017-05-22 15:00:08 UTC
 nchan: 73
 projs: []
 sfreq: 512.0 Hz
 subject_info: 1 item (dict)
```

Unfortunately, I could not upload the .bdf file. If you are willing to check how it looks on your machine, the data is from following source: https://osf.io/tjx93 the first subject file. 

Thank you for your help!

**Comment by agramfort** [comment]
I don't manage to download the full zip file. I tried 3 times and it's
always corrupted. Can you put the file on dropbox/gdrive/wetransfer?

**Comment by SeHellmann** [comment]
You should be able to download a ZIP with only the first subject data here (available until November 12):
https://faubox.rrze.uni-erlangen.de/getlink/fi54TvWEboLofdx7qNCM6p/SBJ_01.zip

**Comment by agramfort** [comment]
sounds like a timezone issue. Are you doing this on the same machine? Each machine assumes a given timezone and this can interact with what you report.

<img width="955" alt="Screenshot 2024-09-13 at 15 46 07" src="https://github.com/user-attachments/assets/485b41b5-1758-418c-8f78-58c87191deb4">

**Comment by SeHellmann** [comment]
I realized both my R and python object have an attribute first_samp, which is 0 in R, too:
```
> raw$first_samp
[1] 0
> raw$info['meas_date']
[1] "2017-05-22 15:00:08 UTC"
```
I also assumed that it may be a timezone issue, because my machine works on UTC+2, but also in R, the timedate is explicitly in UTC, so I would hope that my own timezone is not used.

**Comment by agramfort** [comment]
can you try to debug this? change your local time zone on your machine and see if it has any impact? look where the datetime object is instantiated in the BDF reader and track the place where the time zone is not explicitly controlled?

**Comment by SeHellmann** [comment]
After changing my system time zone, the printed time was correct, so I suppose it is just an issue of converting the output for print. 

In addition, after setting my time zone back to my actual time zone and only printing the onset column of the annotations data frame, I see that the time is actually represented correctly:
```
> raw$annotations$to_data_frame()$onset
[1] "2017-05-22 17:00:08 CEST" "2017-05-22 17:01:10 CEST" "2017-05-22 17:01:38 CEST"
```

I also managed to find the error in other R-python related things. In the end, my problem was that in R, the original command `ica.exclude.extend([8, 9])` is not translatable to `ica$exclude$extend(c(8,9))`, which gives an error of trying to apply a non-function.
Thanks for your help.
